FROM node:20 AS base
WORKDIR /app
RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

# Copy all source files
COPY . .

# Build the application to create the .next directory
RUN pnpm run build

FROM node:20-alpine3.19 as release
WORKDIR /app
RUN npm i -g pnpm

# Copy only the necessary files for production
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next

# Copy the source files that are needed
COPY --from=base /app/src ./src

EXPOSE 3000

# Start the application in production mode
CMD ["pnpm", "start"]